//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HanyAddressBookGet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Employee
    {
        public int EmpID { get; set; }
        [Display(Name = "Name")]
        public string EmpName { get; set; }
        [Display(Name = "Title")]
        public Nullable<int> TitleID { get; set; }
        [Display(Name = "Department")]
        public Nullable<int> DeptID { get; set; }
        [Display(Name = "Mobile")]
        [DataType(DataType.PhoneNumber)]
        public string EmpMobile { get; set; }
        [Display(Name = "Home Telephone")]
        [DataType(DataType.PhoneNumber)]
        public string EmpHomeTel { get; set; }
        [Display(Name = "Date Of birth")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> EmpDateofBirth { get; set; }
        [Display(Name = "Address")]
        public string EmpAddress { get; set; }
        [Display(Name = "Email Address")]
        [DataType(DataType.EmailAddress)]
        public string EmpEmail { get; set; }
        [Display(Name = "Photo")]
        public byte[] EmpPhoto { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Title Title { get; set; }
    }
}
